kind: pipeline
name: default

steps:
  - name: Install dependencies
    image: node:carbon-alpine
    commands:
      - yarn

  - name: Lint
    image: node:carbon-alpine
    commands:
      - yarn lint

  - name: Test
    image: node:carbon-alpine
    commands:
      - yarn test

  - name: Build
    image: node:carbon-alpine
    commands:
      - yarn build

  - name: Publish
    image: node:carbon-alpine
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - apk add --no-cache git
      - yarn semantic-release
    when:
      branch:
        - master
        - alpha
        - beta

when:
  event:
    - push
