kind: pipeline
name: default

steps:
  - name: Install dependencies
    image: node:carbon
    commands:
      - yarn

  - name: Lint
    image: node:carbon
    commands:
      - yarn lint

  - name: Test
    image: node:carbon
    commands:
      - yarn test

  - name: Build
    image: node:carbon
    commands:
      - yarn build

  - name: Publish
    image: node:carbon
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - yarn semantic-release --ci=false
    when:
      branch:
        - master
        - alpha
        - beta

trigger:
  event:
    # Only build for Pushes to Branches
    exclude:
      - pull_request
      - tag
